# Generated by Django 5.0.3 on 2024-07-31 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0003_alter_cart_item_quantity'),
        ('item_app', '0002_alter_item_category_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='item_app.item'),
        ),
    ]
