name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up PostgreSQL
      run: |
        sudo apt-get update
        sudo apt-get install postgresql -y
        sudo apt-get install postgresql-contrib -y
        sudo apt-get install postgresql-client -y
        echo waiting...
        sleep 6
        sudo service postgresql start
        sudo su - postgres -c "psql --echo-all -U postgres -d postgres --command \"CREATE USER runner WITH SUPERUSER CREATEDB CREATEROLE LOGIN PASSWORD '';\""
        sudo su - postgres -c "psql --echo-all -U postgres -d postgres --command \"create database ecom_db;\""
        echo finished pg commands...
        sudo service postgresql restart
    - name: Set up Python
      run: |
        sudo apt install python3
        sudo apt-get install python3-pip
    - name: Install dependencies
      run: pip install -r ecom_proj/requirements.txt
    - name: Migrations
      run: |
        python ecom_proj/manage.py makemigrations
        python ecom_proj/manage.py migrate
    - name: Autograder
      uses: education/autograding@v1
      continue-on-error: true
 